runner:
  latexlint-by-draftcheck:
    # draftcheck all files
    cmd: |
        echo "THIS IS TEST!!"
        for file in $(find . -type d \( -path './node_modules' \) -prune -false -o -iname '*.tex');
        do
          echo "filename := ${file}"
          draftcheck ${file}
        done
    errorformat:
      - '%E%f:%l:%c: %.%#'
      - '%C%p^%#'
      - '%C%\s%+%m'
    level: warning
