name: Pull Request Comment

on:
  pull_request:
#    types: [opened]

jobs:
  comment:
    name: Comment when open pull request
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run GitHub API
        run: |
          cat comment.txt
          m=AAA
          m="${m//'%'/'%25'}"
          m="${m//$'\n'/'%0A'}"
          m="${m//$'\r'/'%0D'}"
          curl -X POST \
               -H "Content-Type: application/json" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -d "{ \"body\": \"${{ env.m }}\" }" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
